# Generated by Django 4.2.27 on 2026-02-01 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ORBIT', '0002_event_date_alter_event_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='数字が小さい順に並びます', verbose_name='表示順')),
                ('number', models.CharField(help_text='例: A-1, 101 など', max_length=10, verbose_name='プログラム番号')),
                ('name', models.CharField(max_length=200, verbose_name='プログラム名')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='ORBIT.event', verbose_name='大会')),
            ],
            options={
                'verbose_name': 'プログラム',
                'verbose_name_plural': 'プログラム',
                'ordering': ['order'],
            },
        ),
    ]
