# Generated by Django 4.2.27 on 2026-02-01 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORBIT', '0003_program'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名前')),
                ('grade', models.PositiveSmallIntegerField(choices=[(1, '中学1年'), (2, '中学2年'), (3, '中学3年'), (4, '高校1年'), (5, '高校2年'), (6, '高校3年'), (0, 'その他')], default=1, verbose_name='学年')),
                ('kana', models.CharField(blank=True, max_length=100, verbose_name='ふりがな')),
            ],
            options={
                'verbose_name': '登録メンバー',
                'verbose_name_plural': '登録メンバー',
                'ordering': ['grade', 'kana'],
            },
        ),
    ]
