# Generated by Django 4.2.27 on 2026-02-02 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORBIT', '0004_participant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participant',
            options={'ordering': ['grade', 'family_kana', 'first_kana'], 'verbose_name': '登録メンバー', 'verbose_name_plural': '登録メンバー'},
        ),
        migrations.RemoveField(
            model_name='participant',
            name='kana',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='name',
        ),
        migrations.AddField(
            model_name='participant',
            name='family_kana',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='せい'),
        ),
        migrations.AddField(
            model_name='participant',
            name='family_name',
            field=models.CharField(default='temp', max_length=100, verbose_name='姓'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participant',
            name='first_kana',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='めい'),
        ),
        migrations.AddField(
            model_name='participant',
            name='first_name',
            field=models.CharField(default='temp', max_length=100, verbose_name='名'),
            preserve_default=False,
        ),
    ]
