# Generated by Django 4.2.27 on 2026-02-02 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ORBIT', '0005_alter_participant_options_remove_participant_kana_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='member_ann',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs_ann', to='ORBIT.participant', verbose_name='ANN'),
        ),
        migrations.AddField(
            model_name='program',
            name='member_c',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs_c', to='ORBIT.participant', verbose_name='C'),
        ),
        migrations.AddField(
            model_name='program',
            name='member_d',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs_d', to='ORBIT.participant', verbose_name='D'),
        ),
    ]
