# Generated by Django 4.2.27 on 2026-02-02 08:32

import ORBIT.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORBIT', '0006_program_member_ann_program_member_c_program_member_d'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='manuscript_pdf',
            field=models.FileField(blank=True, null=True, upload_to=ORBIT.models.program_pdf_path, verbose_name='原稿PDF'),
        ),
    ]
