# Generated by Django 4.2.27 on 2026-02-02 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORBIT', '0007_program_manuscript_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='プログラム名'),
        ),
        migrations.AlterField(
            model_name='program',
            name='number',
            field=models.CharField(help_text='例: A-1, 101 など', max_length=10, null=True, verbose_name='プログラム番号'),
        ),
    ]
