# Generated by Django 4.2.27 on 2026-02-02 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORBIT', '0009_alter_program_name_alter_program_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'イベント・常設枠'},
        ),
        migrations.AddField(
            model_name='event',
            name='is_permanent',
            field=models.BooleanField(default=False, verbose_name='常設（通年）'),
        ),
        migrations.AddField(
            model_name='fiscalyear',
            name='is_current',
            field=models.BooleanField(default=False, verbose_name='現在の年度'),
        ),
    ]
