# Generated by Django 4.2.27 on 2026-02-02 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ORBIT', '0010_alter_event_options_event_is_permanent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='fiscal_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='ORBIT.fiscalyear', verbose_name='年度'),
        ),
    ]
