# Generated by Django 4.2.27 on 2026-02-02 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ORBIT', '0011_alter_event_fiscal_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before_text', models.TextField(verbose_name='変更前')),
                ('after_text', models.TextField(verbose_name='変更後')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='ORBIT.program')),
            ],
        ),
        migrations.CreateModel(
            name='DirectorInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=50, verbose_name='アイコン名')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORBIT.event')),
            ],
        ),
    ]
